collections:
  "Marvel Cinematic Universe": {tpdb_poster: 143466}
set:
  "Ant-Man (2015)": {tpdb_poster: 114067}
  "Ant-Man and the Wasp (2018)": {tpdb_poster: 114075}
  "Ant-Man and the Wasp: Quantumania (2023)": {tpdb_poster: 295039}
  "Avengers: Age of Ultron (2015)": {tpdb_poster: 114066}
  "Avengers: Endgame (2019)": {tpdb_poster: 114077}
  "Avengers: Infinity War (2018)": {tpdb_poster: 114074}
  "Black Panther (2018)": {tpdb_poster: 114073}
  "Black Panther: Wakanda Forever (2022)": {tpdb_poster: 282452}
  "Black Widow (2021)": {tpdb_poster: 114079}
  "Captain America: Civil War (2016)": {tpdb_poster: 114068}
  "Captain America: The First Avenger (2011)": {tpdb_poster: 114060}
  "Captain America: The Winter Soldier (2014)": {tpdb_poster: 114064}
  "Captain Marvel (2019)": {tpdb_poster: 114076}
  "Doctor Strange (2016)": {tpdb_poster: 114069}
  "Doctor Strange in the Multiverse of Madness (2022)": {tpdb_poster: 221996}
  "Eternals (2021)": {tpdb_poster: 170975}
  "Guardians of the Galaxy (2014)": {tpdb_poster: 114065}
  "Guardians of the Galaxy Vol. 2 (2017)": {tpdb_poster: 114070}
  "Guardians of the Galaxy Volume 3 (2023)": {tpdb_poster: 320089}
  "Iron Man (2008)": {tpdb_poster: 114056}
  "Iron Man 2 (2010)": {tpdb_poster: 114058}
  "Iron Man 3 (2013)": {tpdb_poster: 114062}
  "Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer (2011)": {tpdb_poster: 139058}
  "Marvel One-Shot: Agent Carter (2013)": {tpdb_poster: 139060}
  "Marvel One-Shot: All Hail the King (2014)": {tpdb_poster: 139061}
  "Marvel One-Shot: Item 47 (2012)": {tpdb_poster: 139059}
  "Marvel One-Shot: The Consultant (2011)": {tpdb_poster: 139057}
  "One Shot: Peter's To-Do List": {tpdb_poster: 139486}
  "One Shot: Team Darryl": {tpdb_poster: 139485}
  "One Shot: Team Thor Part 2": {tpdb_poster: 139484}
  "One Shot: Team Thor": {tpdb_poster: 139483}
  "Shang-Chi and the Legend of the Ten Rings (2021)": {tpdb_poster: 167286}
  "Spider-Man: Far From Home (2019)": {tpdb_poster: 114078}
  "Spider-Man: Homecoming (2017)": {tpdb_poster: 114071}
  "Spider-Man: No Way Home (2021)": {tpdb_poster: 188298}
  "Spider-Man: No Way Home (The More Fun Stuff Version) (2021)": {tpdb_poster: 287942}
  "The Avengers (2012)": {tpdb_poster: 114061}
  "The Guardians of the Galaxy Holiday Special (2022)": {tpdb_poster: 291149}
  "The Incredible Hulk (2008)": {tpdb_poster: 114057}
  "Thor (2011)": {tpdb_poster: 114059}
  "Thor: Love and Thunder (2022)": {tpdb_poster: 249716}
  "Thor: Ragnarok (2017)": {tpdb_poster: 114072}
  "Thor: The Dark World (2013)": {tpdb_poster: 114063}
  "Werewolf by Night (2022)": {tpdb_poster: 274755}
