collections:
  "Middle-Earth Collection": {poster_tpdb: 191451}
set:
  "The Lord of the Rings: The Fellowship of the Ring (2001)": {poster_tpdb: 191454}
  "The Lord of the Rings: The Two Towers (2002)": {poster_tpdb: 191455}
  "The Lord of the Rings: The Return of the King (2003)": {poster_tpdb: 191456}
  "The Hobbit: An Unexpected Journey (2012)": {poster_tpdb: 191457}
  "The Hobbit: The Desolation of Smaug (2013)": {poster_tpdb: 191458}
  "The Hobbit: The Battle of the Five Armies (2014)": {poster_tpdb: 191459}
