collections:
  "Indiana Jones Collection": {tpdb_poster: 53303}
set:
  "Raiders of the Lost Ark (1981)": {tpdb_poster: 53304}
  "Indiana Jones and the Temple of Doom (1984)": {tpdb_poster: 53305}
  "Indiana Jones and the Last Crusade (1989)": {tpdb_poster: 53306}
  "Indiana Jones and the Kingdom of the Crystal Skull (2008)": {tpdb_poster: 53307}