collections:
  "The Godfather Collection": {tpdb_poster: 312507}
set:
  "The Godfather (1972)": {tpdb_poster: 312508}
  "The Godfather: Part II (1974)": {tpdb_poster: 312509}
  "The Godfather: Part III (1990)": {tpdb_poster: 312510}
  "The Godfather Coda: The Death of Michael Corleone (1990)": {tpdb_poster: 312511}