collections:
  "In Association with Marvel": {tpdb_poster: 125372}
  "The Amazing Spider-Man Collection": {tpdb_poster: 132632}
  "Spider-Man Collection": {tpdb_poster: 132628}
  "Spider-Man: Spider-Verse Collection": {tpdb_poster: 132635}
  "Deadpool Collection": {tpdb_poster: 135778}
  "Blade Collection": {tpdb_poster: 139554}
  "X-Men Collection": {tpdb_poster: 143883}
  "Wolverine Collection": {tpdb_poster: 143893}
  "The Punisher Collection": {tpdb_poster: 151892}
  "Fantastic Four Collection": {tpdb_poster: 151994}
  "Daredevil Collection": {tpdb_poster: 152033}
  "Ghost Rider Collection": {tpdb_poster: 152105}
  "Spider-Man Universe": {tpdb_poster: 132627}

set:
  "Big Hero 6 (2014)": {tpdb_poster: 171459}
  "X-Men (2000)": {tpdb_poster: 143884}
  "X2 (2003)": {tpdb_poster: 143885}
  "X-Men: The Last Stand (2006)": {tpdb_poster: 143886}
  "X-Men Origins: Wolverine (2009)": {tpdb_poster: 143894}
  "X-Men: First Class (2011)": {tpdb_poster: 143887}
  "The Wolverine (2013)": {tpdb_poster: 143895}
  "X-Men: Days of Future Past (2014)": {tpdb_poster: 143888}
  "X-Men: Days of Future Past (The Rogue Cut)": {tpdb_poster: 143892}
  "Deadpool (2016)": {tpdb_poster: 135779}
  "Deadpool: No Good Deed": {tpdb_poster: 135784}
  "X-Men: Apocalypse (2016)": {tpdb_poster: 143889}
  "Logan (2017)": {tpdb_poster: 143896}
  "Logan (Noir)": {tpdb_poster: 143897}
  "Deadpool 2 (2018)": {tpdb_poster: 135780}
  "Deadpool 2 (Super Duper Cut)": {tpdb_poster: 135783}
  "Once Upon a Deadpool (2018)": {tpdb_poster: 135781}
  "Dark Phoenix (2019)": {tpdb_poster: 143890}
  "The New Mutants (2020)": {tpdb_poster: 143891}
  "Spider-Man: Into the Spider-Verse (2018)": {tpdb_poster: 132636}
  "Spider-Man: Across the Spider-Verse (2023)": {tpdb_poster: null}
  "Spider-Ham: Caught in a Ham (2019)": {tpdb_poster: 132639}
  "Spider-Man: All Roads Lead to No Way Home": {tpdb_poster: 287943}
  "Venom (2018)": {tpdb_poster: 132638}
  "Morbius (2022)": {tpdb_poster: 235304}
  "Venom: Let There Be Carnage (2021)": {tpdb_poster: 153724}
  "Fantastic Four (2015)": {tpdb_poster: 151997}
  "The Amazing Spider-Man (2012)": {tpdb_poster: 132633}
  "The Amazing Spider-Man 2 (2014)": {tpdb_poster: 132634}
  "Ghost Rider (2007)": {tpdb_poster: 152106}
  "Ghost Rider: Spirit of Vengeance (2011)": {tpdb_poster: 152107}
  "The Punisher (2004)": {tpdb_poster: 151894}
  "Punisher: War Zone (2008)": {tpdb_poster: 151895}
  "Fantastic Four (2005)": {tpdb_poster: 151995}
  "Fantastic Four: Rise of the Silver Surfer (2007)": {tpdb_poster: 151996}
  "Spider-Man (2002)": {tpdb_poster: 132629}
  "Spider-Man 2 (2004)": {tpdb_poster: 132630}
  "Spider-Man 3 (2007)": {tpdb_poster: 132631}
  "Elektra (2005)": {tpdb_poster: 152035}
  "Blade (1998)": {tpdb_poster: 139555}
  "Blade II (2002)": {tpdb_poster: 139556}
  "Blade: Trinity (2004)": {tpdb_poster: 139557}
  "Hulk (2003)": {tpdb_poster: 139467}
  "Daredevil (2003)": {tpdb_poster: 152034}
  "Nick Fury: Agent of S.H.I.E.L.D. (1998)": {tpdb_poster: 220282}
  "The Fantastic Four (1994)": {tpdb_poster: 164762}
